const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://images.pexels.com/photos/718739/pexels-photo-718739.jpeg?cs=srgb&dl=pexels-sydney-troxell-718739.jpg&fm=jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg?cs=srgb&dl=pexels-valeria-boltneva-1639562.jpg&fm=jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?cs=srgb&dl=pexels-photomix-company-103566.jpg&fm=jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://images.pexels.com/photos/5528982/pexels-photo-5528982.jpeg?cs=srgb&dl=pexels-zen-chung-5528982.jpg&fm=jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://images.pexels.com/photos/4124830/pexels-photo-4124830.jpeg?cs=srgb&dl=pexels-jill-wellington-4124830.jpg&fm=jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://images.pexels.com/photos/6413383/pexels-photo-6413383.jpeg?cs=srgb&dl=pexels-rodnae-productions-6413383.jpg&fm=jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.pexels.com/photos/59943/pexels-photo-59943.jpeg?cs=srgb&dl=pexels-salo-al-59943.jpg&fm=jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?cs=srgb&dl=pexels-ella-olsson-1640770.jpg&fm=jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://images.pexels.com/photos/452737/pexels-photo-452737.jpeg?cs=srgb&dl=pexels-artem-beliaikin-452737.jpg&fm=jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  